services:
  yanix-website:
    image: yanix-website:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yanix-website
    network_mode: host
    environment:
      NODE_ENV: production
      PORT: "3001"
      DATABASE_URL: "mysql://appuser:apppass@127.0.0.1:3306/appdb"

volumes:
  mysql_data:

